# Generated by Django 3.2.4 on 2021-06-11 13:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.TextField(blank=True, null=True, verbose_name='Observed species')),
                ('original_url', models.URLField(blank=True, null=True, verbose_name='Original url of the observation, if available')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='Observation picture')),
                ('origin', models.TextField(blank=True, null=True, verbose_name='Source of the original observation')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'ordering': ('id',),
            },
        ),
    ]
