# Generated by Django 3.2.4 on 2021-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Observation date'),
        ),
        migrations.AddField(
            model_name='observation',
            name='record_creation_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
