# Generated by Django 3.2.4 on 2021-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210611_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_string',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observation date in string format'),
        ),
    ]
