# Generated by Django 3.2.4 on 2021-06-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_observation_observation_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='observation_string',
            new_name='observation_time_string',
        ),
    ]
