# Generated by Django 3.2.4 on 2022-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_observation_string_observation_observation_time_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ('species',), 'verbose_name': 'observation', 'verbose_name_plural': 'observations'},
        ),
        migrations.AddField(
            model_name='observation',
            name='native_id',
            field=models.TextField(blank=True, null=True, verbose_name='Id of the observation in its native app'),
        ),
    ]
