# Generated by Django 3.2.4 on 2022-02-16 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220216_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateTimeField(default=datetime.datetime(2022, 2, 16, 15, 17, 46, 470085, tzinfo=utc))),
                ('event_finish', models.DateTimeField(blank=True, null=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='datafiles')),
                ('origin', models.TextField(blank=True, null=True, verbose_name='Source of the original observation')),
            ],
            options={
                'verbose_name': 'loadevent',
                'verbose_name_plural': 'loadevents',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='load_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.loadevent'),
        ),
    ]
