# Generated by Django 3.2.4 on 2022-03-30 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220216_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadevent',
            name='data_file',
        ),
        migrations.AddField(
            model_name='loadevent',
            name='data_chunks',
            field=models.TextField(blank=True, null=True, verbose_name='List of succesully created local pages'),
        ),
        migrations.AlterField(
            model_name='loadevent',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 53, 55, 200364, tzinfo=utc)),
        ),
    ]
