# Generated by Django 3.2.4 on 2022-03-31 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220330_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Observation date year month day'),
        ),
        migrations.AlterField(
            model_name='loadevent',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 8, 45, 14, 510983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Observation datetime'),
        ),
    ]
