# Generated by Django 3.2.4 on 2022-03-31 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220331_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ('species_id',), 'verbose_name': 'observation', 'verbose_name_plural': 'observations'},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='species',
        ),
        migrations.AddField(
            model_name='observation',
            name='species_guess',
            field=models.TextField(blank=True, null=True, verbose_name='Guessed species'),
        ),
        migrations.AddField(
            model_name='observation',
            name='species_id',
            field=models.TextField(blank=True, null=True, verbose_name='Species identified'),
        ),
        migrations.AlterField(
            model_name='loadevent',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 9, 7, 44, 605751, tzinfo=utc)),
        ),
    ]
