# Generated by Django 3.2.4 on 2022-04-01 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220401_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadevent',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
