# Generated by Django 3.2.4 on 2022-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_loadevent_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Observation last update'),
        ),
    ]
