# Generated by Django 3.2.4 on 2022-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_observation_observation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Observation last update'),
        ),
    ]
