# Generated by Django 3.2.4 on 2022-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_observation_observation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadevent',
            name='max_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum loaded id value for event'),
        ),
    ]
