# Generated by Django 3.2.4 on 2022-04-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_loadevent_max_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadevent',
            name='min_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum loaded id value for event'),
        ),
    ]
