# Generated by Django 3.2.4 on 2022-04-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220404_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Project name')),
                ('slug', models.TextField(blank=True, null=True, verbose_name='Shortened project name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Project url if available')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_observations', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataproject')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region')),
            ],
        ),
    ]
