# Generated by Django 3.2.4 on 2022-04-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_stats_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.TextField(blank=True, null=True, verbose_name='Region slug'),
        ),
    ]
