# Generated by Django 3.2.4 on 2022-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='iconic_taxon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='iconic_taxon_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
