# Generated by Django 3.2.4 on 2022-05-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220509_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
